### ISSUE TITLE
Two tabs have the same title on editor page

### ISSUE THREAD

**Issue by xiaoyu3x** [intel/zephyrjs-ide#196]
**Issue description**
Two tabs have the same title on editor page

**Current behavior**
There are two the same name tabs on the TabBar.

**Expected behavior**
Don't allow two tabs to have the same title.

**Steps to reproduce**
1.Launch the IDE and connect to the board device.
2.Edit two files 'a.js' and 'A.js'.
3.Click "Save" button and rename 'A.js' as 'a.js' to save.
4.Check whether or not exist two 'a.js' on the TabBar.
  
![selection_021](https://user-images.githubusercontent.com/17694094/31643566-dbd2a1a4-b323-11e7-8510-55d697a37a19.png)

**'JS IDE for Zephyr OS' version:** `X.Y.Z / abcd1234`
v0.21.0-alpha / [2796b09](https://github.com/01org/zephyrjs-ide/commit/2796b09bd1d4e87cdad5d4304d7cb66b70600cfa)

 **Comment**
Prompt dialog doesn't popup when two files of the same name are saved on the TabBar

**Comment by brianjjones** [comment]
The IDE now will show a red highlight if you try and rename it to something that already exists, indicating you can't name it the same thing.
