### ISSUE TITLE
Simple space should not be allowed as a tab's name on editor page

### ISSUE THREAD

**Issue by xiaoyu3x** [intel/zephyrjs-ide#219]
**Issue description**
When a existing tab name is modified as space->' ',  this tab's name can't will be modified again. 

**Current behavior**
Simple space is allowed as tab's name on editor page.

**Expected behavior**
Simple space should not be allowed as tab's name on editor page.

**Steps to reproduce**
1. Launch the IDE.
2. Edit a non-empty files 'a.js'.
3. Use space replaces a.js name.
![selection_041](https://user-images.githubusercontent.com/17694094/35209267-e4db62a8-ff87-11e7-8985-1073b48f3fa0.png)

![selection_040](https://user-images.githubusercontent.com/17694094/35209210-722898de-ff87-11e7-9b55-de7a31a8e038.png)

**'JS IDE for Zephyr OS' version:** `X.Y.Z / abcd1234`
v0.22.0-alpha / [deb9d90](https://github.com/intel/zephyrjs-ide/commit/deb9d90c4b4a1bff526b4fa1fdb66d85774ea47a)

**Comment by brianjjones** [comment]
This issue has been fixed.
