### ISSUE TITLE
Redundant information 'Not enough arguments' appears when running 'ls' command in console

### ISSUE THREAD

**Issue by xiaoyu3x** [intel/zephyrjs-ide#226]
**Issue description**
Redundant information 'Not enough arguments' appears when running 'ls' command in console window with  STM32F407G-DISC1 and Olimex STM32-E407 boards. 

**Current behavior**
'Not enough arguments' appears when executing 'ls' command.

**Expected behavior**
No message 'Not enough arguments' appears.

**Steps to reproduce**
1. Build and flash images into boards.
2. Start WebIDE and connect boards. 
3. Execute command 'ls'.
![selection_063](https://user-images.githubusercontent.com/17694094/35791560-ac983446-0a83-11e8-9c73-754c63bddc34.png)

**'JS IDE for Zephyr OS' version:** `X.Y.Z / abcd1234`
v0.22.0-alpha / [deb9d90](https://github.com/intel/zephyrjs-ide/commit/deb9d90c4b4a1bff526b4fa1fdb66d85774ea47a)

**Comment by brianjjones** [comment]
The console has been disabled for the IDE, so I'm closing this issue as it's no longer valid.
