### ISSUE TITLE
Fail to run code on WebIDE

### ISSUE THREAD

**Issue by xiaoyu3x** [intel/zephyrjs-ide#236]
**Issue description**
Can't run any file when click 'Run' button on WebIDE.

**Current behavior**
'run: command not found' is popups after click 'Run' button

**Expected behavior**
The file is run successfully and no error throws.

**Steps to reproduce**
1. Build images with commit [ed85a4d](https://github.com/intel/zephyr.js/commit/ed85a4deec7fdc4e6c464ba9bef7c03da3339550) and flash it  into A101 board.
2. Start WebIDE and connect board. 
3. Edit any file on editor window and press 'Run' button.
![selection_078](https://user-images.githubusercontent.com/17694094/36528737-1bc0755c-17f1-11e8-88ed-7f8c93a31811.png)

**'JS IDE for Zephyr OS' version:** `X.Y.Z / abcd1234`
v0.22.0-alpha / [bae9e36](https://github.com/intel/zephyrjs-ide/commit/bae9e368af04efcafd88bf0185792444ea317ae1)

**'Comment**
'Stop' button also is invalid.
![default](https://user-images.githubusercontent.com/17694094/36576516-0701430c-1806-11e8-8fb7-63f10ae07cd7.PNG)

**Comment by xiaoyu3x** [comment]
This issue isn't reproduced with commit 02a08ec, so closed it.

**Comment by brianjjones** [comment]
It works for me using the latest ZJS and IDE v0.23-0-alpha.  @xiaoyu3x could you re-test please?
