### ISSUE TITLE
Redundant character ' } ' and error prompt window appears after saving file failure

### ISSUE THREAD

**Issue by xiaoyu3x** [intel/zephyrjs-ide#242]
**Issue description**
When save some files without the suffix, e.g. "ble" (not ble.js/ble.txt).
In fact, this kind of file hasn't been saved into board.
But system prompt "Saving to device successful" and character ' } '  is printed on console windows

**Current behavior**
Redundant character ' } ' and error prompt window appears after saving file failure.

**Expected behavior**
No character  ' } '  appears and popup "Saving fail" information.

**Steps to reproduce**
1. Build and flash images into board.
2. Start WebIDE and connect board. 
3. Edit any file (e.g."ble") without the suffix and click "Save" button to save file into board.
![screenshot from 2018-04-19 15-12-12](https://user-images.githubusercontent.com/17694094/38977507-2a32d0e0-43e7-11e8-9221-ac4779396a83.png)
![screenshot from 2018-04-19 15-12-32](https://user-images.githubusercontent.com/17694094/38977537-3d104d14-43e7-11e8-95f2-b0de815a962e.png)

**'JS IDE for Zephyr OS' version:** `X.Y.Z / abcd1234`
v0.23.0-alpha / [02a08ec](https://github.com/intel/zephyrjs-ide/commit/02a08ec5c0d0868a98da8a9ef2c012a218a058bd)

**Comment by xiaoyu3x** [comment]
hello, @brianjjones 
I just created "a" file and save it into A101.
The following is result and redundant character ' } ' appears on console window.
![selection_099](https://user-images.githubusercontent.com/17694094/38907868-5b2b0390-42f0-11e8-9465-38b9bc349de3.png)

I use zephyrjs commit [82662d6](https://github.com/intel/zephyr.js/commit/82662d65bb71d3088db9368d390872f9ccf82ede)

**Comment by xiaoyu3x** [comment]
Sorry, @brianjjones 
According to your comment, I retested this issue again and found it that happened only when file is without the suffix.
I just updated this issue.
Thank you.

**Comment by brianjjones** [comment]
@xiaoyu3x This should be fixed in master now with PR #252

**Comment by xiaoyu3x** [comment]
This issue isn't reproduced with commit [6e87086](https://github.com/intel/zephyrjs-ide/commit/6e87086726a83cdfbbfd16e1ecbd1749c059ea79)
