### ISSUE TITLE
File "Accelerometer", "Gyroscope" and "Sensor BLE Demo" need to update as alteration of W3C Generic Sensor API

### ISSUE THREAD

**Issue by xiaoyu3x** [intel/zephyrjs-ide#243]
**Issue description**
In Examples of sidebar, "Accelerometer" , "Gyroscope" and "Sensor BLE Demo" codes need to update.
Need to change 'onchange' to 'onreading' by [new W3C Generic Sensor API](https://dev.fitbit.com/build/reference/device-api/sensors/)

**Current behavior**
"onchange" event has been rename "onreading" in new W3C Generic Sensor API , but it still be used in WebIDE. 

**Expected behavior**
"Accelerometer" , "Gyroscope" and "Sensor BLE Demo" codes need to update, "onchange"  rename "onreading" .

**Steps to reproduce**
Start WebIDE and check  "Accelerometer", "Gyroscope" and "Sensor BLE Demo" in Examples.

**'JS IDE for Zephyr OS' version:** `X.Y.Z / abcd1234`
v0.23.0-alpha / [02a08ec](https://github.com/intel/zephyrjs-ide/commit/02a08ec5c0d0868a98da8a9ef2c012a218a058bd)

**Comment by brianjjones** [comment]
Thanks, I've fixed this in the master branch - but it's not live on the webpage yet.  Once it is, I'll reply here that its ready to be re-tested.

**Comment by brianjjones** [comment]
Fix is now in master.

**Comment by xiaoyu3x** [comment]
This issue isn't reproduced with commit [6e87086](https://github.com/intel/zephyrjs-ide/commit/6e87086726a83cdfbbfd16e1ecbd1749c059ea79)
